version: 0.0
os: linux
files:
  - source: .
    destination: /opt/kamleague/website
hooks:
  ApplicationStop:
    - location: bin/stop
      timeout: 300
  AfterInstall:
    - location: bin/unpack
  ApplicationStart:
    - location: bin/start
      timeout: 3600
  ValidateService:
    - location: bin/healthz
      timeout: 3600
